[project]
name = "sistema-autenticacao-django-rest"
version = "0.1.0"
description = ""
authors = [{ name = "Ian Matheus Veiga", email = "ianmatheusv54@gmail.com" }]
dependencies = ["django>=6.1", "python-dotenv>=1.2.2", "djangorestframework>=3.17.2"]
requires-python = ">=3.14"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
dev = ["pylint-django>=2.8.0"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[tool.pdm]
distribution = false
